### ISSUE TITLE
MLO omap3_beagle not found at rcn-ee.net

### ISSUE THREAD

**Issue by rghisi** [RobertCNelson/flasher#2]
Hi,

I'm trying to update my beagleboard C4 U boot through the tool available in this repository however the MLO-omap3_beagle-v2015.01-r6 file is not found at http://rcn-ee.net/deb/tools/omap3_beagle/MLO-omap3_beagle-v2015.01-r6 .

I've checked other directories under /deb/tools and couldn't find the files for others platforms also. Is there a problem?

Here is the script output:

```
Script Version git: bdec088
-----------------------------

Downloading Device's Bootloader
-----------------------------
2017-01-17 16:48:20 URL:http://rcn-ee.net/deb/tools/latest/bootloader-ng [5361/5361] -> "/tmp/tmp.g6JCcSmtP9/dl/bootloader-ng" [1]
http://rcn-ee.net/deb/tools/omap3_beagle/MLO-omap3_beagle-v2015.01-r6:
2017-01-17 16:48:20 ERRO 404: Not Found.
```

Thank you in advance.

Ricardo

**Comment by RobertCNelson** [comment]
Hi @rghisi , oh this script has really bit-rotted since 2013...

It'll need lots of changes to get things working on today's average distro.

Regards,

**Comment by RobertCNelson** [comment]
looking at the script, just run:

```
nand erase
```
or
```
nand erase.chip
```
and just don't deal with the nand..

Regards,

**Comment by rghisi** [comment]
Thanks @RobertCNelson for the fast feedback and sorry for using this old repo.

Regards,
